### PR TITLE
slightly tweaked header & footer logo positions to be more aligned

### PR DESCRIPTION
**Pull request by phschimm**
Also renamed the 2 image files in `theme/images` for better identification. I think it's more consistent to have the Capgemini logo in the left corner of the header, since it's also in the left corner of the footer.

This change is already implemented in the [getting-started](https://github.com/devonfw/getting-started/) guide and can be previewed [here](https://github.com/devonfw/getting-started/blob/develop/devonfw_getting_started.pdf).

### CODE REVIEW

**Comment by phschimm** [comment]
Thanks for the approval @jambulud.
May I merge these changes or should I wait for input from @maybeec?

**Comment by jambulud** [comment]
There should be no problem if we merge this, it is just the name of two images and the result looks good.

**Comment by maybeec** [comment]
Hi @phschimm,
unfortunately I have to disagree on that. Even further, we should completely remove the capgemini logo from the docs. devonfw is open source and capgemini does not have any interest to be the only one connected with devonfw. This always tend to end up in dicsussions with users, that they fear to finally result in a vendor lock-in, which actually is not true as we are just publishing open source only.
@sjimenez77 hope you agree.

**Comment by phschimm** [comment]
Ah damn, I didn't see your comment @maybeec before I hit merge. :sweat:
But I can do that right away and create another PR if that's fine.

**Comment by maybeec** [comment]
Np, could be easily reverted in that case. Let's just wait some more seconds for @sjimenez77 comment in case he has a different view, which I barely doubt.

**Comment by ivanderk** [comment]
We should remove the capgemini name and logo from all of the pages apart from one where we *must* mention that *devonfw is copyright Capgemini and a registered trademark*. We *might* mention capgemini name and logo at something to a "About us" or "Sponsor" page

**Comment by sjimenez77** [comment]
Thanks @ivanderk, @maybeec. 
I agree with your points. Let's go then for this solution. 

Please @phschimm, let's do the following:

1. Remove Capgemini logo from the header/footer.
2. Edit contents at https://github.com/devonfw/devonfw-guide/blob/master/general/getting-started-what-is-devonfw.asciidoc and include the Capgemini logo and mention that _"devonfw is copyright Capgemini and a registered trademark"_. Maybe we can do in the Introduction section ath the very beginning of the document. 

Thanks!

**Pull request merged**
