### PR TITLE
update of the "Contributing" chapter

### PR DESCRIPTION
**Pull request by phschimm**
* included the organizations [.github](https://github.com/devonfw/.github) repo as a submodule
* removed deprecated contents from the "Contributing" chapter
* included contents from [.github](https://github.com/devonfw/.github) submodule in the "Contributing" chapter  

Local testing resulted in [this PDF](https://teams.microsoft.com/l/file/9B2893AA-78C9-4595-A3FE-20B148FCA8A0?tenantId=76a2ae5a-9f00-4f6b-95ed-5d33d77c4d61&fileType=pdf&objectUrl=https%3A%2F%2Fcapgemini.sharepoint.com%2Fsites%2FDevonEasyInstall%2FShared%20Documents%2FGeneral%2Fmaster.pdf&baseUrl=https%3A%2F%2Fcapgemini.sharepoint.com%2Fsites%2FDevonEasyInstall&serviceName=teams&threadId=19:83a6329b25ff493cb6eb66cd44d614fa@thread.skype&groupId=c7dc11ca-3fc0-4d7d-8466-a5416111b1ec) (please request access on [MS Teams](https://teams.microsoft.com/l/team/19%3a83a6329b25ff493cb6eb66cd44d614fa%40thread.skype/conversations?groupId=c7dc11ca-3fc0-4d7d-8466-a5416111b1ec&tenantId=76a2ae5a-9f00-4f6b-95ed-5d33d77c4d61) if necessary).

### CODE REVIEW

**Comment by phschimm** [comment]
The Travis CI build is failing because it's only configured for the `master` branch.
It should pass once the working-branch has been merged with `master`.

**Comment by sjimenez77** [comment]
Please, check and resolve the conflicts @phschimm 

Thanks!

**Comment by sjimenez77** [comment]
Hi @phschimm,

Everything looks fine. The only thing pending, that I don't know if it was part of this PR or not, is to **extract** the _devonfw Introduction_ and _Why should I use devonfw?_ to a new **Introduction** section. 

Could you please confirm this?

Thanks!

**Comment by phschimm** [comment]
> Hi @phschimm,
> 
> Everything looks fine. The only thing pending, that I don't know if it was part of this PR or not, is to **extract** the _devonfw Introduction_ and _Why should I use devonfw?_ to a new **Introduction** section.
> 
> Could you please confirm this?
> 
> Thanks!

Hi @sjimenez77,
yes, I'm preparing those changes at the moment and will include them in my next PR together with the the getting-started rework, since they are better suited to be commited under that topic. :+1:

**Pull request merged**
